accountId: kmpySmUISimoRrJL6NL73w
delegateToken: 2f6b0988b6fb3370073c3d0505baee59
managerUrl: https://localhost:9090/api/
verificationServiceUrl: https://localhost:7070/verification/
cvNextGenUrl: https://localhost:6060/cv/api/
heartbeatIntervalMs: 60000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: true
grpcServiceConnectorPort: 8080
logStreamingServiceBaseUrl: http://localhost:8079
clientToolsDownloadDisabled: false
installClientToolsInBackground: true
INIT_SCRIPT: |-
  apt-get update;
  echo
  if which jq; then
    echo found jq shreyas
    echo
  else
    echo installing jq shreyas
    echo
    apt-get install -y jq
  fi
  echo

# Required for local development as manger uses self-signed cert
trustAllCertificates: true
